- hosts: localhost
  connection: local

  vars:
    homebrew_packages:
#      - { name: awscli }
#      - { name: cdrtools }
      - { name: colordiff }
      - { name: coreutils }
      - { name: curl }
      - { name: gh }
      - { name: git }
      - { name: gnu-sed }
      - { name: gnupg }
      - { name: grep }
      - { name: htop }
      - { name: jq }
      - { name: mas }
#      - { name: packer }
      - { name: speedtest-cli }
      - { name: telnet }
      - { name: terraform }
      - { name: tree }
      - { name: vim }
      - { name: watch }
      - { name: wget }
      - { name: zsh }

  tasks:
    - name: homebrew update
      community.general.homebrew:
        update_homebrew: true

# brew
    - name: homebrew packages install
      community.general.homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_packages }}'